# Generated by Django 4.1.6 on 2023-02-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_date_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='style',
            field=models.IntegerField(null=True),
        ),
    ]
