# Generated by Django 4.1.6 on 2023-02-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='style',
            field=models.IntegerField(verbose_name=4),
        ),
    ]
