# Generated by Django 4.1.6 on 2023-02-13 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_comment_approved_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='style',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
