# Generated by Django 4.1.6 on 2023-03-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Kommentare'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Blogbeiträge'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='style',
        ),
    ]
