# Generated by Django 4.1.6 on 2023-03-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='einleitung',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
