# Generated by Django 4.1.6 on 2023-03-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_post_einleitung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='einleitung',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
